In [1]:
# === CONFIGURACIÃ“N INICIAL OBLIGATORIA ===
import sys
print("VersiÃ³n de Python:", sys.version)

import tensorflow as tf
print("GPU disponible:", tf.config.list_physical_devices('GPU'))

!pip install seaborn plotly

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report
import warnings
warnings.filterwarnings('ignore')

plt.style.use('default')
sns.set_palette("husl")
plt.rcParams['figure.figsize'] = (10, 6)
plt.rcParams['font.size'] = 12

print("âœ… Entorno configurado correctamente en Google Colab")

VersiÃ³n de Python: 3.11.13 (main, Jun  4 2025, 08:57:29) [GCC 11.4.0]
GPU disponible: []
Requirement already satisfied: seaborn in /usr/local/lib/python3.11/dist-packages (0.13.2)
Requirement already satisfied: plotly in /usr/local/lib/python3.11/dist-packages (5.24.1)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in /usr/local/lib/python3.11/dist-packages (from seaborn) (2.0.2)
Requirement already satisfied: pandas>=1.2 in /usr/local/lib/python3.11/dist-packages (from seaborn) (2.2.2)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in /usr/local/lib/python3.11/dist-packages (from seaborn) (3.10.0)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.11/dist-packages (from plotly) (8.5.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from plotly) (24.2)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.2)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.11/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.58.5)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.8)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.11/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (11.2.1)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.2.3)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.11/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
âœ… Entorno configurado correctamente en Google Colab

# ðŸ“Š Notebook 1: Fundamentos de NumPy y Pandas

## Objetivos:
- Manipular arrays con NumPy
- Cargar y procesar datos con Pandas
- ExploraciÃ³n bÃ¡sica de datos

## Dataset: Titanic
Analizaremos los datos del Titanic para entender supervivencia de pasajeros.

In [7]:
# === CARGA DE DATOS ===
# Cargar dataset Titanic
titanic = sns.load_dataset('titanic')

print("InformaciÃ³n del dataset:")
print(f"Forma del dataset: {titanic.shape}")
print(f"Columnas: {list(titanic.columns)}")

# Mostrar primeras filas
print("\nPrimeras 5 filas:")
titanic.head()

InformaciÃ³n del dataset:
Forma del dataset: (891, 15)
Columnas: ['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare', 'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town', 'alive', 'alone']

Primeras 5 filas:

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [9]:
# === EJERCICIOS NUMPY ===

# Crear arrays de ejemplo
edades = np.array(titanic['age'].dropna())
tarifas = np.array(titanic['fare'].dropna())

print("EstadÃ­sticas con NumPy:")
print(f"Edad promedio: {np.mean(edades):.2f}")
print(f"Edad mediana: {np.median(edades):.2f}")
print(f"DesviaciÃ³n estÃ¡ndar edad: {np.std(edades):.2f}")

print(f"\nTarifa promedio: ${np.mean(tarifas):.2f}")
print(f"Tarifa mÃ¡xima: ${np.max(tarifas):.2f}")
print(f"Tarifa mÃ­nima: ${np.min(tarifas):.2f}")

# Operaciones con arrays
edades_normalizadas = (edades - np.mean(edades)) / np.std(edades)
print(f"\nEdades normalizadas (primeras 10): {edades_normalizadas[:10]}")

EstadÃ­sticas con NumPy:
Edad promedio: 29.70
Edad mediana: 28.00
DesviaciÃ³n estÃ¡ndar edad: 14.52

Tarifa promedio: $32.20
Tarifa mÃ¡xima: $512.33
Tarifa mÃ­nima: $0.00

Edades normalizadas (primeras 10): [-0.53037664  0.57183099 -0.25482473  0.36516706  0.36516706  1.67403863
 -1.90813618 -0.18593675 -1.08148046 -1.77036023]

In [10]:
# === EJERCICIOS PANDAS ===

print("Limpieza y transformaciÃ³n de datos:")

# InformaciÃ³n del dataset
print("InformaciÃ³n general:")
print(titanic.info())

print("\nValores nulos por columna:")
print(titanic.isnull().sum())

# EstadÃ­sticas descriptivas
print("\nEstadÃ­sticas descriptivas:")
print(titanic.describe())

# AnÃ¡lisis por categorÃ­as
print("\nSupervivencia por clase:")
supervivencia_clase = titanic.groupby('class')['survived'].agg(['count', 'sum', 'mean'])
supervivencia_clase.columns = ['Total', 'Supervivientes', 'Tasa_Supervivencia']
print(supervivencia_clase)

print("\nSupervivencia por gÃ©nero:")
supervivencia_genero = titanic.groupby('sex')['survived'].agg(['count', 'sum', 'mean'])
supervivencia_genero.columns = ['Total', 'Supervivientes', 'Tasa_Supervivencia']
print(supervivencia_genero)

Limpieza y transformaciÃ³n de datos:
InformaciÃ³n general:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB
None

Valores nulos por columna:
survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

EstadÃ­sticas descriptivas:
         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

Supervivencia por clase:
        Total  Supervivientes  Tasa_Supervivencia
class
First     216             136            0.629630
Second    184              87            0.472826
Third     491             119            0.242363

Supervivencia por gÃ©nero:
        Total  Supervivientes  Tasa_Supervivencia
sex
female    314             233            0.742038
male      577             109            0.188908

In [16]:
# En cada notebook, aÃ±adir celda final para guardar en GitHub
# 1. Conectar Colab con GitHub
from google.colab import auth
auth.authenticate_user()

# 2. Configurar Git
!git config --global user.email "mery.romero@uees.edu.ec"
!git config --global user.name "Mery Romero"

# 3. Clonar tu repositorio
!git clone https://github.com/LorenaRomero-UEES/UEES-IA-Semana1-Romero-Mery.git
%cd UEES-IA-Semana1-Romero-Mery

# 4. Copiar notebook al repositorio
!cp /content/01_Fundamentos_NumPy_Pandas.ipynb ./02_Laboratorio/notebooks/

# 5. Hacer commit y push
!git add .
!git commit -m "AÃ±adir notebook de fundamentos"
!git push origin main

Cloning into 'UEES-IA-Semana1-Romero-Mery'...
remote: Enumerating objects: 15, done.
remote: Counting objects: 100% (15/15), done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 15 (delta 1), reused 0 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (15/15), 11.39 KiB | 11.39 MiB/s, done.
Resolving deltas: 100% (1/1), done.
/content/UEES-IA-Semana1-Romero-Mery/UEES-IA-Semana1-Romero-Mery/UEES-IA-Semana1-Romero-Mery/UEES-IA-Semana1-Romero-Mery
cp: cannot stat '/content/01_Fundamentos_NumPy_Pandas.ipynb': No such file or directory
On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean
fatal: could not read Username for 'https://github.com': No such device or address

In [26]:
# Entra al repo
cd /content/UEES-IA-Semana1-Romero-Mery

# 1) Saca de Git el token y bÃ³rralo del disco
git rm --cached 02_Laboratorio/notebooks/GitHub_Token.txt
rm 02_Laboratorio/notebooks/GitHub_Token.txt

# 2) AÃ±Ã¡delo a .gitignore para que nunca vuelva a colarse
echo "02_Laboratorio/notebooks/GitHub_Token.txt" >> .gitignore
git add .gitignore

# 3) Haz commit de la eliminaciÃ³n
git commit -m "Remove GitHub token file from repo"

# 4) Push normal (ahora ya no hay secretos en el history)
git push origin main

SyntaxError: invalid decimal literal (ipython-input-26-2577950672.py, line 5)

In [25]:
# 1. AutenticaciÃ³n + montaje de Drive
from google.colab import auth, drive
auth.authenticate_user()
drive.mount('/content/drive')

# 3. ConfiguraciÃ³n Git
!git config --global user.email "mery.romero@uees.edu.ec"
!git config --global user.name "Mery Romero"

# 4. Rutas correctas
NOTEBOOK_SRC = "/content/drive/MyDrive/Colab Notebooks/01_Fundamentos_NumPy_Pandas.ipynb"
TOKEN_PATH   = "/content/drive/MyDrive/GitHub_Token.txt"
REPO_URL     = "https://github.com/LorenaRomero-UEES/UEES-IA-Semana1-Romero-Mery.git"
REPO_DIR     = "/content/UEES-IA-Semana1-Romero-Mery"

# 5. Clonar el repo si no existe
import os
if not os.path.isdir(REPO_DIR):
    !git clone {REPO_URL} {REPO_DIR}

# 6. Copiar el notebook al repo
!cp "{NOTEBOOK_SRC}" "{REPO_DIR}/02_Laboratorio/notebooks/"

# 7. Leer tu token y reconfigurar el remote
with open(TOKEN_PATH) as f:
    token = f.read().strip()
!cd {REPO_DIR} && git remote set-url origin https://LorenaRomero-UEES:{token}@github.com/LorenaRomero-UEES/UEES-IA-Semana1-Romero-Mery.git

# 8. Commit & push
!cd {REPO_DIR} && git add .
!cd {REPO_DIR} && git commit -m "AÃ±adir notebook de fundamentos"
!cd {REPO_DIR} && git push origin main

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
[main 81c6ba4] AÃ±adir notebook de fundamentos
 1 file changed, 1 insertion(+), 1 deletion(-)
Enumerating objects: 15, done.
Counting objects: 100% (15/15), done.
Delta compression using up to 2 threads
Compressing objects: 100% (9/9), done.
Writing objects: 100% (11/11), 8.37 KiB | 2.79 MiB/s, done.
Total 11 (delta 3), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (3/3), completed with 1 local object.
remote: error: GH013: Repository rule violations found for refs/heads/main.
remote:
remote: - GITHUB PUSH PROTECTION
remote:   â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”
remote:     Resolve the following violations before pushing again
remote:
remote:     - Push cannot contain secrets
remote:
remote:
remote:      (?) Learn how to resolve a blocked push
remote:      https://docs.github.com/code-security/secret-scanning/working-with-secret-scanning-and-push-protection/working-with-push-protection-from-the-command-line#resolving-a-blocked-push
remote:
remote:
remote:       â€”â€” GitHub Personal Access Token â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”
remote:        locations:
remote:          - commit: 0860b58c8fd07fc58a47e1408428e6b78b48b45b
remote:            path: 02_Laboratorio/notebooks/gh_token.txt:1
remote:
remote:        (?) To push, remove secret from commit(s) or follow this URL to allow the secret.
remote:        https://github.com/LorenaRomero-UEES/UEES-IA-Semana1-Romero-Mery/security/secret-scanning/unblock-secret/2zpxd2xkTbylLs8mGBxoNuLdGo9
remote:
remote:
remote:
To https://github.com/LorenaRomero-UEES/UEES-IA-Semana1-Romero-Mery.git
 ! [remote rejected] main -> main (push declined due to repository rule violations)
error: failed to push some refs to 'https://github.com/LorenaRomero-UEES/UEES-IA-Semana1-Romero-Mery.git'

In [15]:
# FunciÃ³n para guardar automÃ¡ticamente en GitHub
def save_to_github(notebook_name, commit_message="Actualizar notebook"):
    """
    Guarda el notebook actual en GitHub
    """
    !cp /content/{notebook_name} ./02_Laboratorio/notebooks/
    !git add .
    !git commit -m "{commit_message}"
    !git push origin main
    print(f" {notebook_name} guardado en GitHub")

# Usar al final de cada sesiÃ³n de trabajo
save_to_github("01_Fundamentos_NumPy_Pandas.ipynb", "Completar ejercicios de NumPy y Pandas")

cp: cannot stat '/content/01_Fundamentos_NumPy_Pandas.ipynb': No such file or directory
On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean
fatal: could not read Username for 'https://github.com': No such device or address
 01_Fundamentos_NumPy_Pandas.ipynb guardado en GitHub